name: mood_tracker_2
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  flutter_local_notifications: ^13.0.0
  shared_preferences: ^2.0.18
  hive: ^2.2.3
  equatable: ^2.0.5
  uuid: ^3.0.7
  flutter_smart_dialog: ^4.9.0+5
  get_it: ^7.2.0
  intl: ^0.17.0
  easy_localization: ^3.0.1
  path_provider: ^2.0.14
  flutter_rating_bar: ^4.0.1
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
